language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t peterl732/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true peterl732/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: " DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-426715826403"
    bucket_path: "docker-react"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
